//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int id { get; set; }
        public string m_name { get; set; }
        public string m_username { get; set; }
        public string m_mail { get; set; }
        public string m_dp { get; set; }
        public int m_phone { get; set; }
    }
}
