//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int id { get; set; }
        public object Id { get; internal set; }
        public string notice1 { get; set; }
        public string user_type { get; set; }
        public string status { get; set; }
        public System.DateTime datet { get; set; }
        public object Name { get; set; }
    }
}
