//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelwhims.Models.TWdatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Manager
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Please enter manager name.")]
        public string m_name { get; set; }
        [Required(ErrorMessage = "Please enter manager user_name.")]
        public string m_username { get; set; }
        [Required(ErrorMessage = "Required")]
        public string m_mail { get; set; }
        [Required(ErrorMessage = "Please enter manager description.")]
        public string m_dp { get; set; }
        [Required(ErrorMessage = "Required")]
       
        public int m_phone { get; set; }
    }
}
