//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelwhims.Models.TWdatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Notice
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Please enter Notice.")]
        public string notice1 { get; set; }
        [Required(ErrorMessage = "Please enter User Type.")]
        public string user_type { get; set; }
        [Required(ErrorMessage = "Please enter Status.")]
        public string status { get; set; }
        [Required(ErrorMessage = "Please enter dateTime.")]
        public System.DateTime datet { get; set; }
    }
}
