//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int id { get; set; }
        public int cuspacta_id { get; set; }
        public string r_review { get; set; }
        public string name { get; set; }
        public int r_rating { get; set; }
    }
}
