//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Blogcomments = new HashSet<Blogcomment>();
            this.Blogs = new HashSet<Blog>();
        }
    
        public int id { get; set; }
        public string u_username { get; set; }
        public string u_password { get; set; }
        public string u_type { get; set; }
    
        public virtual ICollection<Blogcomment> Blogcomments { get; set; }
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
